language: rust
cache: cargo
script:
  - cargo build --verbose --all --manifest-path proxy/Cargo.toml
  - cargo test --verbose --all --manifest-path proxy/Cargo.toml
  - cargo build --verbose --all --manifest-path worker/Cargo.toml
  - cargo test --verbose --all --manifest-path worker/Cargo.toml
