version: '3'
services:
  queue:
    image: rabbitmq:3-management
    ports:
      - '8080:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  redis:
    image: redis
    ports:
      - '6379:6379'
  influxdb:
    image: influxdb
    ports:
      - '8086:8086' # HTTP API
      - '8083:8083' # Administrator interface port, if enabled
      - '2003:2003' # Graphite support, if enabled
    environment:
      INFLUXDB_DB: "scraper_db"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "root"
      INFLUXDB_ADMIN_PASSWORD: "hunter2"
      INFLUXDB_USER: "worker"
      INFLUXDB_USER_PASSWORD: "password"
