version: '3'
services:
  queue:
    image: rabbitmq:3-management
    ports:
      - '8080:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  redis:
    image: redis
    ports:
      - '6379:6379'